name: Build and Deploy Test Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      # Checkout this project source code
      - uses: actions/checkout@v3
      # Deploy this app using k8s-kurated-addons-action
      - uses: nearform-actions/k8s-kurated-addons-action@main
        # Autodetect everything and use the default 8080 port
